{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 41,
   "id": "f7dcc309",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "import re"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "id": "44841c81",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>URL_ID</th>\n",
       "      <th>URL</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>37</td>\n",
       "      <td>https://insights.blackcoffer.com/ai-in-healthc...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>38</td>\n",
       "      <td>https://insights.blackcoffer.com/what-if-the-c...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>39</td>\n",
       "      <td>https://insights.blackcoffer.com/what-jobs-wil...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>40</td>\n",
       "      <td>https://insights.blackcoffer.com/will-machine-...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>41</td>\n",
       "      <td>https://insights.blackcoffer.com/will-ai-repla...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>109</th>\n",
       "      <td>146</td>\n",
       "      <td>https://insights.blackcoffer.com/blockchain-fo...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>110</th>\n",
       "      <td>147</td>\n",
       "      <td>https://insights.blackcoffer.com/the-future-of...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>111</th>\n",
       "      <td>148</td>\n",
       "      <td>https://insights.blackcoffer.com/big-data-anal...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>112</th>\n",
       "      <td>149</td>\n",
       "      <td>https://insights.blackcoffer.com/business-anal...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>113</th>\n",
       "      <td>150</td>\n",
       "      <td>https://insights.blackcoffer.com/challenges-an...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>114 rows × 2 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     URL_ID                                                URL\n",
       "0        37  https://insights.blackcoffer.com/ai-in-healthc...\n",
       "1        38  https://insights.blackcoffer.com/what-if-the-c...\n",
       "2        39  https://insights.blackcoffer.com/what-jobs-wil...\n",
       "3        40  https://insights.blackcoffer.com/will-machine-...\n",
       "4        41  https://insights.blackcoffer.com/will-ai-repla...\n",
       "..      ...                                                ...\n",
       "109     146  https://insights.blackcoffer.com/blockchain-fo...\n",
       "110     147  https://insights.blackcoffer.com/the-future-of...\n",
       "111     148  https://insights.blackcoffer.com/big-data-anal...\n",
       "112     149  https://insights.blackcoffer.com/business-anal...\n",
       "113     150  https://insights.blackcoffer.com/challenges-an...\n",
       "\n",
       "[114 rows x 2 columns]"
      ]
     },
     "execution_count": 42,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "urls=pd.read_excel(r\"E:\\Black_Coffer_Assignment\\Input.xlsx\")\n",
    "urls"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "id": "564ae5e9",
   "metadata": {},
   "outputs": [],
   "source": [
    "path=r\"E:/Black_Coffer_Assignment/Web_Scrapped_Articles/\"\n",
    "for i in range(0,len(urls)):\n",
    "    position=i\n",
    "    row=urls.iloc[position]\n",
    "    url_id=row[0]\n",
    "    url=row[1]\n",
    "    agent = {\"User-Agent\": 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36'}\n",
    "    page=requests.get(url, headers=agent)\n",
    "    soup=BeautifulSoup(page.content,'html.parser')\n",
    "    if len(list(soup.findAll(attrs = {\"class\":\"td-post-content\"})))!=0:\n",
    "        Title=BeautifulSoup(page.content,'html.parser').h1.text\n",
    "        Article=soup.findAll(attrs = {\"class\":\"td-post-content\"})[0].text.replace(\"\\n\",\" \")\n",
    "        content=[Title, Article]\n",
    "        f = open(path+''+str(url_id)+\".txt\", 'w')\n",
    "        f.write(' '.join(content))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d68595c9",
   "metadata": {},
   "source": [
    "Stop_Words"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "id": "9a2c35c1",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "path1=r'E:/Black_Coffer_Assignment/StopWords'\n",
    "all_files = os.listdir(path1)\n",
    "\n",
    "new_list=[]\n",
    "for fle in all_files:\n",
    "    with open(os.path.join(path1, fle),\"rb\") as f:\n",
    "        text = f.read()\n",
    "        new_list.append(text)\n",
    "\n",
    "stopwords=str(new_list).replace(\"\\\\n\",\" \").replace(\"\\\\r\",\" \").replace(\"|\",\"\").replace(\",\",\n",
    "            '').replace(\"b'\",'').replace(\"'\",'').replace(\"[\",'').replace(\"]\",'').strip().lower().split()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 45,
   "id": "e9fa87ba",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "14238"
      ]
     },
     "execution_count": 45,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "len(stopwords)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6e74229e",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "id": "795c19e8",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "path3=r'E:/Black_Coffer_Assignment/MasterDictionary/'\n",
    "all_files2 = os.listdir(path3)\n",
    "\n",
    "negative=open(path3+all_files2[0],'rb').read()\n",
    "negative_words=str(negative).replace(\"\\\\n\",\" \").replace(\"\\\\r\",\" \").replace(\"|\",\"\").replace(\",\",\n",
    "            '').replace(\"b'\",'').replace(\"'\",'').replace(\"[\",'').replace(\"]\",'').strip().lower().split()\n",
    "\n",
    "positive=open(path3+all_files2[1],'rb').read()\n",
    "positive_words=str(positive).replace(\"\\\\n\",\" \").replace(\"\\\\r\",\" \").replace(\"|\",\"\").replace(\",\",\n",
    "            '').replace(\"b'\",'').replace(\"'\",'').replace(\"[\",'').replace(\"]\",'').strip().lower().split()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a2c0a6b3",
   "metadata": {},
   "source": [
    "Positive Score, Negative Score, Polarity Score, Subjectivity Score"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "id": "a39e8bd1",
   "metadata": {},
   "outputs": [],
   "source": [
    "word_dict = {'Positive':[], 'Negative':[]}\n",
    "def add_values_in_dict(word_dict, key, list_of_words):\n",
    "    if key not in word_dict:\n",
    "        word_dict[key] = list()\n",
    "    word_dict[key].append(list_of_words)\n",
    "    return word_dict"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "id": "ebb0eab7",
   "metadata": {},
   "outputs": [],
   "source": [
    "def count_syllables(word):\n",
    "    c = 0\n",
    "    vowels = 'aeiou'\n",
    "    l = re.findall(f'(?!e$)(?!es$)(?!ed$)[{vowels}]', word, re.I)\n",
    "    return len(l)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "id": "8e9fe4a7",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import json\n",
    "path2=r'E:/Black_Coffer_Assignment/Web_Scrapped_Articles/'\n",
    "all_files1 = os.listdir(path2)\n",
    "\n",
    "positive_score=[]\n",
    "negative_score=[]\n",
    "polarity_score=[]\n",
    "subjectivity_score=[]\n",
    "url_ids=[]\n",
    "syllable_count=[]\n",
    "\n",
    "for file in all_files1:\n",
    "    url_ids.append(int(file.replace(\".txt\",'')))\n",
    "    with open(os.path.join(path2, file),\"rb\") as p:\n",
    "        text1 = p.read()\n",
    "        text2=str(text1).lower().replace(\"/\",\n",
    "                        ' ').replace(\"b'\",' ').replace(\"\\\\\",' ').replace(\".\",\n",
    "                        ' ').replace(\":\",\" \").replace(\"%\",' ').replace(\"-\",\n",
    "                        ' ').replace(\",\",' ').replace(\"$\",\" \").replace(\"[\",' ').replace(\"]\",\n",
    "                        ' ').replace(\"(\",' ').replace(\")\",' ').replace(\"!\",' ').replace(\"\\'\",\n",
    "                        ' ').replace(\"&\",' ').replace(\"xe2\",\" \").replace(\"x80\",' ').replace(\"x93\",' ').replace(\"x99\",\n",
    "                        ' ').replace(\"x98\",' ').replace(\"xc2 xa0 xc2 xa0\",' ').replace(\"xc2 xa0\",' ').replace(\"x9c\",\n",
    "                        ' ').replace(\"x9d\",' ').replace(\"?\",' ').replace(\"x94\",' ').replace(\"fy20\",\n",
    "                        ' ').replace(\"fy21\",' ').replace(\"fy22\",' ').replace(\"xa6\",' ').replace(\"*\",' ').strip().split()\n",
    "        pos=0\n",
    "        neg=0\n",
    "        pol=0\n",
    "        cleaned_word=0\n",
    "        for word in text2:\n",
    "            if word not in stopwords:\n",
    "                cleaned_word=cleaned_word+1\n",
    "                list1 = []\n",
    "                list1.append(count_syllables(word))\n",
    "                if word in positive_words:\n",
    "                    word_dict = add_values_in_dict(word_dict, 'Positive', word)\n",
    "                    pos=pos+1\n",
    "                elif word in negative_words:\n",
    "                    word_dict = add_values_in_dict(word_dict, 'Negative', word)\n",
    "                    neg=neg-1\n",
    "        pol = (pos - (neg*-1))/ ((pos + (neg*-1)) + 0.000001)\n",
    "        sub = (pos + (neg*-1))/ (cleaned_word + 0.000001)\n",
    "        \n",
    "    file1 = open(r'E:\\Black_Coffer_Assignment\\dictionary.json', 'w')  #Creating Dictionary of Positive and Negative Words\n",
    "    json.dump(word_dict,file1)\n",
    "    file1.close()\n",
    "    \n",
    "    positive_score.append(pos)      #Positive Score\n",
    "    negative_score.append(neg*-1)   #Negative Score\n",
    "    polarity_score.append(pol)      #Polarity Score\n",
    "    subjectivity_score.append(sub)  #Subjectivity Score\n",
    "    syllable_count.append(sum(list1)/len(list1))  #Syllable count"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 76,
   "id": "0f0ddb51",
   "metadata": {},
   "outputs": [],
   "source": [
    "df1=pd.DataFrame({'URL_ID':url_ids,'POSITIVE SCORE':positive_score, \n",
    "                  'NEGATIVE SCORE':negative_score, 'POLARITY SCORE':polarity_score,\n",
    "                 'SUBJECTIVITY SCORE':subjectivity_score})\n",
    "\n",
    "df3=pd.DataFrame({'URL_ID':url_ids, 'SYLLABLE PER WORD':syllable_count})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d4fef845",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "9b83a7e1",
   "metadata": {},
   "source": [
    "Average Sentence Length, Percentage of Complex Words, Fog Index, Complex Word Count, Word Count, Personal Pronoun, Average Word Lenth "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "id": "a89bc3e9",
   "metadata": {},
   "outputs": [],
   "source": [
    "def count_complex_words(words_list):\n",
    "    c = 0\n",
    "    for word in words_list:\n",
    "        l = re.findall('(?!e$)[aeiou]+', word, re.I)+re.findall('^[aeiouy]*e$', word, re.I)\n",
    "        if len(l) > 2:\n",
    "            c += 1\n",
    "    return c"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "id": "903ed4e4",
   "metadata": {},
   "outputs": [],
   "source": [
    "def count_personal_pronouns(text):\n",
    "    pronoun_count = re.compile(r'\\b(I|we|ours|my|mine|(?-i:us))\\b', re.I)\n",
    "    pronouns = pronoun_count.findall(text)\n",
    "    return len(pronouns)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "id": "22e9df7f",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[nltk_data] Downloading package punkt to\n",
      "[nltk_data]     C:\\Users\\sudip\\AppData\\Roaming\\nltk_data...\n",
      "[nltk_data]   Package punkt is already up-to-date!\n"
     ]
    }
   ],
   "source": [
    "avg_sent_length = []\n",
    "percent_of_complex_words = []\n",
    "fog_index = []\n",
    "url_idss = []\n",
    "no_of_complex_word=[]\n",
    "word_count=[]\n",
    "personal_pronouns_count = []\n",
    "word_avg_length = []\n",
    "\n",
    "import nltk\n",
    "nltk.download('punkt')\n",
    "from nltk.tokenize import word_tokenize, sent_tokenize\n",
    "path3=r'E:/Black_Coffer_Assignment/Web_Scrapped_Articles/'\n",
    "for file in all_files1:\n",
    "    url_idss.append(int(file.replace(\".txt\",'')))\n",
    "    with open(os.path.join(path3, file),\"rb\") as q:\n",
    "        text3 = q.read()\n",
    "        word_tk=word_tokenize(str(text3))\n",
    "        sent_tk=sent_tokenize(str(text3))\n",
    "        avg_sent_length.append(len(word_tk)/len(sent_tk))\n",
    "        percent_of_complex_words.append(count_complex_words(word_tk)/len(word_tk))\n",
    "        fog_index.append(0.4*(len(word_tk)/len(sent_tk))+(count_complex_words(word_tk)/len(word_tk)))\n",
    "        no_of_complex_word.append(count_complex_words(word_tk))\n",
    "        word_count.append(len(word_tk))\n",
    "    c = 0\n",
    "    for word in word_tk:\n",
    "        c += len(word)\n",
    "    personal_pronouns_count.append(count_personal_pronouns(str(text3)))\n",
    "    word_avg_length.append(round(c/len(word_tk)))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 79,
   "id": "eedf3c09",
   "metadata": {},
   "outputs": [],
   "source": [
    "df2=pd.DataFrame({'URL_ID':url_idss,'AVG SENTENCE LENGTH': avg_sent_length, \n",
    "                  'PERCENTAGE OF COMPLEX WORDS':percent_of_complex_words,\n",
    "                 'FOG INDEX':fog_index, 'AVG NUMBER OF WORDS PER SENTENCE': avg_sent_length,\n",
    "                 'COMPLEX WORD COUNT': no_of_complex_word, 'WORD COUNT': word_count})\n",
    "\n",
    "df4=pd.DataFrame({'URL_ID':url_idss, 'PERSONAL PRONOUNS':personal_pronouns_count, 'AVG WORD LENGTH':word_avg_length})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 91,
   "id": "df880f47",
   "metadata": {},
   "outputs": [],
   "source": [
    "output1=pd.merge(urls, df1, on = \"URL_ID\", how = \"outer\")\n",
    "output2=pd.merge(output1, df2, on=\"URL_ID\", how=\"outer\")\n",
    "output3=pd.merge(output2, df3, on=\"URL_ID\", how=\"outer\")\n",
    "Final_Output=pd.merge(output3, df4, on=\"URL_ID\", how=\"outer\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 96,
   "id": "6bb5b714",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>URL_ID</th>\n",
       "      <th>URL</th>\n",
       "      <th>POSITIVE SCORE</th>\n",
       "      <th>NEGATIVE SCORE</th>\n",
       "      <th>POLARITY SCORE</th>\n",
       "      <th>SUBJECTIVITY SCORE</th>\n",
       "      <th>AVG SENTENCE LENGTH</th>\n",
       "      <th>PERCENTAGE OF COMPLEX WORDS</th>\n",
       "      <th>FOG INDEX</th>\n",
       "      <th>AVG NUMBER OF WORDS PER SENTENCE</th>\n",
       "      <th>COMPLEX WORD COUNT</th>\n",
       "      <th>WORD COUNT</th>\n",
       "      <th>SYLLABLE PER WORD</th>\n",
       "      <th>PERSONAL PRONOUNS</th>\n",
       "      <th>AVG WORD LENGTH</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>37</td>\n",
       "      <td>https://insights.blackcoffer.com/ai-in-healthc...</td>\n",
       "      <td>66.0</td>\n",
       "      <td>34.0</td>\n",
       "      <td>0.320000</td>\n",
       "      <td>0.100100</td>\n",
       "      <td>26.626667</td>\n",
       "      <td>0.222834</td>\n",
       "      <td>10.873501</td>\n",
       "      <td>26.626667</td>\n",
       "      <td>445.0</td>\n",
       "      <td>1997.0</td>\n",
       "      <td>4.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>5.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>38</td>\n",
       "      <td>https://insights.blackcoffer.com/what-if-the-c...</td>\n",
       "      <td>58.0</td>\n",
       "      <td>37.0</td>\n",
       "      <td>0.221053</td>\n",
       "      <td>0.163230</td>\n",
       "      <td>20.922078</td>\n",
       "      <td>0.150838</td>\n",
       "      <td>8.519669</td>\n",
       "      <td>20.922078</td>\n",
       "      <td>243.0</td>\n",
       "      <td>1611.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>7.0</td>\n",
       "      <td>5.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>39</td>\n",
       "      <td>https://insights.blackcoffer.com/what-jobs-wil...</td>\n",
       "      <td>65.0</td>\n",
       "      <td>35.0</td>\n",
       "      <td>0.300000</td>\n",
       "      <td>0.117096</td>\n",
       "      <td>22.678571</td>\n",
       "      <td>0.208399</td>\n",
       "      <td>9.279828</td>\n",
       "      <td>22.678571</td>\n",
       "      <td>397.0</td>\n",
       "      <td>1905.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>3.0</td>\n",
       "      <td>5.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>40</td>\n",
       "      <td>https://insights.blackcoffer.com/will-machine-...</td>\n",
       "      <td>66.0</td>\n",
       "      <td>28.0</td>\n",
       "      <td>0.404255</td>\n",
       "      <td>0.141353</td>\n",
       "      <td>19.763441</td>\n",
       "      <td>0.136017</td>\n",
       "      <td>8.041394</td>\n",
       "      <td>19.763441</td>\n",
       "      <td>250.0</td>\n",
       "      <td>1838.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>17.0</td>\n",
       "      <td>5.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>41</td>\n",
       "      <td>https://insights.blackcoffer.com/will-ai-repla...</td>\n",
       "      <td>60.0</td>\n",
       "      <td>27.0</td>\n",
       "      <td>0.379310</td>\n",
       "      <td>0.104067</td>\n",
       "      <td>29.151515</td>\n",
       "      <td>0.175156</td>\n",
       "      <td>11.835762</td>\n",
       "      <td>29.151515</td>\n",
       "      <td>337.0</td>\n",
       "      <td>1924.0</td>\n",
       "      <td>4.0</td>\n",
       "      <td>16.0</td>\n",
       "      <td>5.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>109</th>\n",
       "      <td>146</td>\n",
       "      <td>https://insights.blackcoffer.com/blockchain-fo...</td>\n",
       "      <td>22.0</td>\n",
       "      <td>28.0</td>\n",
       "      <td>-0.120000</td>\n",
       "      <td>0.108225</td>\n",
       "      <td>20.387755</td>\n",
       "      <td>0.184184</td>\n",
       "      <td>8.339286</td>\n",
       "      <td>20.387755</td>\n",
       "      <td>184.0</td>\n",
       "      <td>999.0</td>\n",
       "      <td>3.0</td>\n",
       "      <td>9.0</td>\n",
       "      <td>5.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>110</th>\n",
       "      <td>147</td>\n",
       "      <td>https://insights.blackcoffer.com/the-future-of...</td>\n",
       "      <td>36.0</td>\n",
       "      <td>15.0</td>\n",
       "      <td>0.411765</td>\n",
       "      <td>0.063670</td>\n",
       "      <td>28.274194</td>\n",
       "      <td>0.159726</td>\n",
       "      <td>11.469404</td>\n",
       "      <td>28.274194</td>\n",
       "      <td>280.0</td>\n",
       "      <td>1753.0</td>\n",
       "      <td>3.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>5.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>111</th>\n",
       "      <td>148</td>\n",
       "      <td>https://insights.blackcoffer.com/big-data-anal...</td>\n",
       "      <td>28.0</td>\n",
       "      <td>47.0</td>\n",
       "      <td>-0.253333</td>\n",
       "      <td>0.120773</td>\n",
       "      <td>20.580645</td>\n",
       "      <td>0.187304</td>\n",
       "      <td>8.419562</td>\n",
       "      <td>20.580645</td>\n",
       "      <td>239.0</td>\n",
       "      <td>1276.0</td>\n",
       "      <td>3.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>5.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>112</th>\n",
       "      <td>149</td>\n",
       "      <td>https://insights.blackcoffer.com/business-anal...</td>\n",
       "      <td>35.0</td>\n",
       "      <td>7.0</td>\n",
       "      <td>0.666667</td>\n",
       "      <td>0.109375</td>\n",
       "      <td>31.120000</td>\n",
       "      <td>0.259640</td>\n",
       "      <td>12.707640</td>\n",
       "      <td>31.120000</td>\n",
       "      <td>202.0</td>\n",
       "      <td>778.0</td>\n",
       "      <td>3.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>6.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>113</th>\n",
       "      <td>150</td>\n",
       "      <td>https://insights.blackcoffer.com/challenges-an...</td>\n",
       "      <td>31.0</td>\n",
       "      <td>40.0</td>\n",
       "      <td>-0.126761</td>\n",
       "      <td>0.136015</td>\n",
       "      <td>17.439394</td>\n",
       "      <td>0.170287</td>\n",
       "      <td>7.146044</td>\n",
       "      <td>17.439394</td>\n",
       "      <td>196.0</td>\n",
       "      <td>1151.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>8.0</td>\n",
       "      <td>5.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>114 rows × 15 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     URL_ID                                                URL  \\\n",
       "0        37  https://insights.blackcoffer.com/ai-in-healthc...   \n",
       "1        38  https://insights.blackcoffer.com/what-if-the-c...   \n",
       "2        39  https://insights.blackcoffer.com/what-jobs-wil...   \n",
       "3        40  https://insights.blackcoffer.com/will-machine-...   \n",
       "4        41  https://insights.blackcoffer.com/will-ai-repla...   \n",
       "..      ...                                                ...   \n",
       "109     146  https://insights.blackcoffer.com/blockchain-fo...   \n",
       "110     147  https://insights.blackcoffer.com/the-future-of...   \n",
       "111     148  https://insights.blackcoffer.com/big-data-anal...   \n",
       "112     149  https://insights.blackcoffer.com/business-anal...   \n",
       "113     150  https://insights.blackcoffer.com/challenges-an...   \n",
       "\n",
       "     POSITIVE SCORE  NEGATIVE SCORE  POLARITY SCORE  SUBJECTIVITY SCORE  \\\n",
       "0              66.0            34.0        0.320000            0.100100   \n",
       "1              58.0            37.0        0.221053            0.163230   \n",
       "2              65.0            35.0        0.300000            0.117096   \n",
       "3              66.0            28.0        0.404255            0.141353   \n",
       "4              60.0            27.0        0.379310            0.104067   \n",
       "..              ...             ...             ...                 ...   \n",
       "109            22.0            28.0       -0.120000            0.108225   \n",
       "110            36.0            15.0        0.411765            0.063670   \n",
       "111            28.0            47.0       -0.253333            0.120773   \n",
       "112            35.0             7.0        0.666667            0.109375   \n",
       "113            31.0            40.0       -0.126761            0.136015   \n",
       "\n",
       "     AVG SENTENCE LENGTH  PERCENTAGE OF COMPLEX WORDS  FOG INDEX  \\\n",
       "0              26.626667                     0.222834  10.873501   \n",
       "1              20.922078                     0.150838   8.519669   \n",
       "2              22.678571                     0.208399   9.279828   \n",
       "3              19.763441                     0.136017   8.041394   \n",
       "4              29.151515                     0.175156  11.835762   \n",
       "..                   ...                          ...        ...   \n",
       "109            20.387755                     0.184184   8.339286   \n",
       "110            28.274194                     0.159726  11.469404   \n",
       "111            20.580645                     0.187304   8.419562   \n",
       "112            31.120000                     0.259640  12.707640   \n",
       "113            17.439394                     0.170287   7.146044   \n",
       "\n",
       "     AVG NUMBER OF WORDS PER SENTENCE  COMPLEX WORD COUNT  WORD COUNT  \\\n",
       "0                           26.626667               445.0      1997.0   \n",
       "1                           20.922078               243.0      1611.0   \n",
       "2                           22.678571               397.0      1905.0   \n",
       "3                           19.763441               250.0      1838.0   \n",
       "4                           29.151515               337.0      1924.0   \n",
       "..                                ...                 ...         ...   \n",
       "109                         20.387755               184.0       999.0   \n",
       "110                         28.274194               280.0      1753.0   \n",
       "111                         20.580645               239.0      1276.0   \n",
       "112                         31.120000               202.0       778.0   \n",
       "113                         17.439394               196.0      1151.0   \n",
       "\n",
       "     SYLLABLE PER WORD  PERSONAL PRONOUNS  AVG WORD LENGTH  \n",
       "0                  4.0                1.0              5.0  \n",
       "1                  2.0                7.0              5.0  \n",
       "2                  2.0                3.0              5.0  \n",
       "3                  2.0               17.0              5.0  \n",
       "4                  4.0               16.0              5.0  \n",
       "..                 ...                ...              ...  \n",
       "109                3.0                9.0              5.0  \n",
       "110                3.0                2.0              5.0  \n",
       "111                3.0                2.0              5.0  \n",
       "112                3.0                0.0              6.0  \n",
       "113                1.0                8.0              5.0  \n",
       "\n",
       "[114 rows x 15 columns]"
      ]
     },
     "execution_count": 96,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "Final_Output"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 95,
   "id": "c354b503",
   "metadata": {},
   "outputs": [],
   "source": [
    "Final_Output.to_excel('E:\\Black_Coffer_Assignment\\Output Data Structure.xlsx', index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "04b0e604",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
